version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 6
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.2
  - dependency-name: webmock
    versions:
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: actionview
    versions:
    - 5.2.4.5
