# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zest-publisher 0.0.9 ruby lib

Gem::Specification.new do |s|
  s.name = "zest-publisher"
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Smartesting R&D"]
  s.date = "2014-09-11"
  s.description = "Provides a command-line tool that generates Java, Python or Ruby code to run the tests."
  s.email = "zest@smartesting.com"
  s.executables = ["zest-publisher"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/templates/common/booleanliteral.hbs",
    "lib/templates/common/dataset.hbs",
    "lib/templates/common/datatable.hbs",
    "lib/templates/common/nullliteral.hbs",
    "lib/templates/common/numericliteral.hbs",
    "lib/templates/common/stringliteral.hbs",
    "lib/templates/common/variable.hbs",
    "lib/templates/java/actionword.hbs",
    "lib/templates/java/actionwords.hbs",
    "lib/templates/java/argument.hbs",
    "lib/templates/java/assign.hbs",
    "lib/templates/java/binaryexpression.hbs",
    "lib/templates/java/call.hbs",
    "lib/templates/java/dict.hbs",
    "lib/templates/java/field.hbs",
    "lib/templates/java/ifthen.hbs",
    "lib/templates/java/index.hbs",
    "lib/templates/java/list.hbs",
    "lib/templates/java/nullliteral.hbs",
    "lib/templates/java/output_config",
    "lib/templates/java/parameter.hbs",
    "lib/templates/java/parenthesis.hbs",
    "lib/templates/java/property.hbs",
    "lib/templates/java/scenario.hbs",
    "lib/templates/java/scenarios.hbs",
    "lib/templates/java/step.hbs",
    "lib/templates/java/stringliteral.hbs",
    "lib/templates/java/tag.hbs",
    "lib/templates/java/template.hbs",
    "lib/templates/java/unaryexpression.hbs",
    "lib/templates/java/variable.hbs",
    "lib/templates/java/while.hbs",
    "lib/templates/python/actionword.hbs",
    "lib/templates/python/actionwords.hbs",
    "lib/templates/python/argument.hbs",
    "lib/templates/python/assign.hbs",
    "lib/templates/python/binaryexpression.hbs",
    "lib/templates/python/call.hbs",
    "lib/templates/python/dict.hbs",
    "lib/templates/python/field.hbs",
    "lib/templates/python/ifthen.hbs",
    "lib/templates/python/index.hbs",
    "lib/templates/python/list.hbs",
    "lib/templates/python/nullliteral.hbs",
    "lib/templates/python/output_config",
    "lib/templates/python/parameter.hbs",
    "lib/templates/python/parenthesis.hbs",
    "lib/templates/python/project.hbs",
    "lib/templates/python/property.hbs",
    "lib/templates/python/scenario.hbs",
    "lib/templates/python/scenarios.hbs",
    "lib/templates/python/step.hbs",
    "lib/templates/python/tag.hbs",
    "lib/templates/python/template.hbs",
    "lib/templates/python/unaryexpression.hbs",
    "lib/templates/python/while.hbs",
    "lib/templates/ruby/actionword.hbs",
    "lib/templates/ruby/actionwords.hbs",
    "lib/templates/ruby/argument.hbs",
    "lib/templates/ruby/assign.hbs",
    "lib/templates/ruby/binaryexpression.hbs",
    "lib/templates/ruby/call.hbs",
    "lib/templates/ruby/dict.hbs",
    "lib/templates/ruby/field.hbs",
    "lib/templates/ruby/ifthen.hbs",
    "lib/templates/ruby/index.hbs",
    "lib/templates/ruby/list.hbs",
    "lib/templates/ruby/minitest/scenario.hbs",
    "lib/templates/ruby/minitest/scenarios.hbs",
    "lib/templates/ruby/minitest/single_scenario.hbs",
    "lib/templates/ruby/output_config",
    "lib/templates/ruby/parameter.hbs",
    "lib/templates/ruby/parenthesis.hbs",
    "lib/templates/ruby/project.hbs",
    "lib/templates/ruby/property.hbs",
    "lib/templates/ruby/scenario.hbs",
    "lib/templates/ruby/scenarios.hbs",
    "lib/templates/ruby/step.hbs",
    "lib/templates/ruby/tag.hbs",
    "lib/templates/ruby/template.hbs",
    "lib/templates/ruby/unaryexpression.hbs",
    "lib/templates/ruby/while.hbs",
    "lib/zest-publisher.rb",
    "lib/zest-publisher/handlebars_helper.rb",
    "lib/zest-publisher/nodes.rb",
    "lib/zest-publisher/nodes_walker.rb",
    "lib/zest-publisher/options_parser.rb",
    "lib/zest-publisher/parameter_type_adder.rb",
    "lib/zest-publisher/render_context_maker.rb",
    "lib/zest-publisher/renderer.rb",
    "lib/zest-publisher/string.rb",
    "lib/zest-publisher/utils.rb",
    "lib/zest-publisher/xml_parser.rb"
  ]
  s.homepage = "https://www.zest-testing.com"
  s.licenses = ["GPL 2"]
  s.rubygems_version = "2.2.2"
  s.summary = "Export your tests from Zest into executable tests."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>, [">= 0.7.3", "~> 0.7"])
      s.add_runtime_dependency(%q<parseconfig>, [">= 1.0.4", "~> 1.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.6.9", "~> 0.6"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.6.2.1", "~> 1.6.2"])
      s.add_runtime_dependency(%q<handlebars>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 3.0.0", "~> 3.0"])
      s.add_development_dependency(%q<rspec-mocks>, [">= 3.0.1", "~> 3.0"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, [">= 0.3.0", "~> 0.3"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    else
      s.add_dependency(%q<colorize>, [">= 0.7.3", "~> 0.7"])
      s.add_dependency(%q<parseconfig>, [">= 1.0.4", "~> 1.0"])
      s.add_dependency(%q<i18n>, [">= 0.6.9", "~> 0.6"])
      s.add_dependency(%q<nokogiri>, [">= 1.6.2.1", "~> 1.6.2"])
      s.add_dependency(%q<handlebars>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 3.0.0", "~> 3.0"])
      s.add_dependency(%q<rspec-mocks>, [">= 3.0.1", "~> 3.0"])
      s.add_dependency(%q<codeclimate-test-reporter>, [">= 0.3.0", "~> 0.3"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    end
  else
    s.add_dependency(%q<colorize>, [">= 0.7.3", "~> 0.7"])
    s.add_dependency(%q<parseconfig>, [">= 1.0.4", "~> 1.0"])
    s.add_dependency(%q<i18n>, [">= 0.6.9", "~> 0.6"])
    s.add_dependency(%q<nokogiri>, [">= 1.6.2.1", "~> 1.6.2"])
    s.add_dependency(%q<handlebars>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 3.0.0", "~> 3.0"])
    s.add_dependency(%q<rspec-mocks>, [">= 3.0.1", "~> 3.0"])
    s.add_dependency(%q<codeclimate-test-reporter>, [">= 0.3.0", "~> 0.3"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
  end
end

