# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: zest-publisher 0.0.7 ruby lib

Gem::Specification.new do |s|
  s.name = "zest-publisher"
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Smartesting R&D"]
  s.date = "2014-05-23"
  s.description = "Provides a command-line tool that generates Python or Ruby code to run the tests."
  s.email = "zest@smartesting.com"
  s.executables = ["zest-publisher"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/templates/common/booleanliteral.erb",
    "lib/templates/common/nullliteral.erb",
    "lib/templates/common/numericliteral.erb",
    "lib/templates/common/stringliteral.erb",
    "lib/templates/common/variable.erb",
    "lib/templates/python/actionword.erb",
    "lib/templates/python/actionwords.erb",
    "lib/templates/python/argument.erb",
    "lib/templates/python/assign.erb",
    "lib/templates/python/binaryexpression.erb",
    "lib/templates/python/call.erb",
    "lib/templates/python/dict.erb",
    "lib/templates/python/field.erb",
    "lib/templates/python/ifthen.erb",
    "lib/templates/python/index.erb",
    "lib/templates/python/list.erb",
    "lib/templates/python/nullliteral.erb",
    "lib/templates/python/output_config",
    "lib/templates/python/parameter.erb",
    "lib/templates/python/parenthesis.erb",
    "lib/templates/python/project.erb",
    "lib/templates/python/property.erb",
    "lib/templates/python/scenario.erb",
    "lib/templates/python/scenarios.erb",
    "lib/templates/python/step.erb",
    "lib/templates/python/tag.erb",
    "lib/templates/python/template.erb",
    "lib/templates/python/unaryexpression.erb",
    "lib/templates/python/while.erb",
    "lib/templates/ruby/actionword.erb",
    "lib/templates/ruby/actionwords.erb",
    "lib/templates/ruby/argument.erb",
    "lib/templates/ruby/assign.erb",
    "lib/templates/ruby/binaryexpression.erb",
    "lib/templates/ruby/call.erb",
    "lib/templates/ruby/dict.erb",
    "lib/templates/ruby/field.erb",
    "lib/templates/ruby/ifthen.erb",
    "lib/templates/ruby/index.erb",
    "lib/templates/ruby/list.erb",
    "lib/templates/ruby/minitest/scenario.erb",
    "lib/templates/ruby/minitest/scenarios.erb",
    "lib/templates/ruby/output_config",
    "lib/templates/ruby/parameter.erb",
    "lib/templates/ruby/parenthesis.erb",
    "lib/templates/ruby/project.erb",
    "lib/templates/ruby/property.erb",
    "lib/templates/ruby/scenario.erb",
    "lib/templates/ruby/scenarios.erb",
    "lib/templates/ruby/step.erb",
    "lib/templates/ruby/tag.erb",
    "lib/templates/ruby/template.erb",
    "lib/templates/ruby/unaryexpression.erb",
    "lib/templates/ruby/while.erb",
    "lib/zest-publisher.rb",
    "lib/zest-publisher/nodes.rb",
    "lib/zest-publisher/options_parser.rb",
    "lib/zest-publisher/string.rb",
    "lib/zest-publisher/utils.rb",
    "lib/zest-publisher/xml_parser.rb"
  ]
  s.homepage = "https://www.zest-testing.com"
  s.licenses = ["GPL 2"]
  s.rubygems_version = "2.2.2"
  s.summary = "Export your tests from Zest into executable tests."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<colorize>, [">= 0.7.3", "~> 0.7"])
      s.add_runtime_dependency(%q<parseconfig>, [">= 1.0.4", "~> 1.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0.6.9", "~> 0.6"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.6.2.1", "~> 1.6.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.14.1", "~> 2.14"])
      s.add_development_dependency(%q<rspec-mocks>, [">= 2.14.6", "~> 2.14"])
      s.add_development_dependency(%q<codeclimate-test-reporter>, [">= 0.3.0", "~> 0.3"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    else
      s.add_dependency(%q<colorize>, [">= 0.7.3", "~> 0.7"])
      s.add_dependency(%q<parseconfig>, [">= 1.0.4", "~> 1.0"])
      s.add_dependency(%q<i18n>, [">= 0.6.9", "~> 0.6"])
      s.add_dependency(%q<nokogiri>, [">= 1.6.2.1", "~> 1.6.2"])
      s.add_dependency(%q<rspec>, [">= 2.14.1", "~> 2.14"])
      s.add_dependency(%q<rspec-mocks>, [">= 2.14.6", "~> 2.14"])
      s.add_dependency(%q<codeclimate-test-reporter>, [">= 0.3.0", "~> 0.3"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
    end
  else
    s.add_dependency(%q<colorize>, [">= 0.7.3", "~> 0.7"])
    s.add_dependency(%q<parseconfig>, [">= 1.0.4", "~> 1.0"])
    s.add_dependency(%q<i18n>, [">= 0.6.9", "~> 0.6"])
    s.add_dependency(%q<nokogiri>, [">= 1.6.2.1", "~> 1.6.2"])
    s.add_dependency(%q<rspec>, [">= 2.14.1", "~> 2.14"])
    s.add_dependency(%q<rspec-mocks>, [">= 2.14.6", "~> 2.14"])
    s.add_dependency(%q<codeclimate-test-reporter>, [">= 0.3.0", "~> 0.3"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0"])
  end
end

