version: 2.1

commands:
  build_and_test:
    description: "Build and run the tests"
    parameters:
      output_dir:
        type: string
        default: ""
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results/<< parameters.output_dir >>
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/<< parameters.output_dir >>/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results/<< parameters.output_dir >>

jobs:
  build-ruby-2_5:
    docker:
      - image: circleci/ruby:2.5.5

    working_directory: ~/repo
    steps:
      - build_and_test:
        output_dir: "2.5"

  build-ruby-2_6:
    docker:
      - image: circleci/ruby:2.6.2

    working_directory: ~/repo
    steps:
      - build_and_test:
        output_dir: "2.6"

workflows:
  version: 2
  build:
    jobs:
      - build-ruby-2_5
      - build-ruby-2_6
